use std::{
    fs,
    path::{Path, PathBuf},
};

const STARTER_MANIFEST_PATH: &str = "src/mastra/mastra.json";
const STARTER_MEMORY_PATH: &str = "src/mastra/memories/default-memory.json";
const STARTER_TOOL_PATH: &str = "src/mastra/tools/demo-sum.json";
const STARTER_AGENT_SPEC_PATH: &str = "src/mastra/agents/demo-agent.json";
const STARTER_AGENT_INSTRUCTIONS_PATH: &str = "src/mastra/agents/demo-agent.md";
const STARTER_WORKFLOW_PATH: &str = "src/mastra/workflows/demo-workflow.json";
const STARTER_PROMPT_PATH: &str = "src/mastra/resources/hello.txt";

pub fn render_manifest(project_name: &str, repo_root: &Path) -> String {
    format!(
        r#"[package]
name = "{project_name}"
version = "0.1.0"
edition = "2024"

[dependencies]
mastra-core = {{ path = "{core_path}" }}
mastra-memory = {{ path = "{memory_path}" }}
mastra-loggers = {{ path = "{loggers_path}" }}
tokio = {{ version = "1.47.1", features = ["full"] }}
"#,
        core_path = repo_root.join("packages/core").display(),
        memory_path = repo_root.join("packages/memory").display(),
        loggers_path = repo_root.join("packages/loggers").display(),
    )
}

pub fn render_main_rs() -> String {
    r#"use std::sync::Arc;

use mastra_core::{Agent, AgentConfig, AgentGenerateRequest, MemoryConfig, RequestContext, StaticModel};
use mastra_loggers::init_tracing;
use mastra_memory::Memory;

const STARTER_MANIFEST: &str = include_str!("mastra/mastra.json");
const DEMO_TOOL_SPEC: &str = include_str!("mastra/tools/demo-sum.json");
const DEMO_WORKFLOW_SPEC: &str = include_str!("mastra/workflows/demo-workflow.json");
const DEMO_AGENT_INSTRUCTIONS: &str = include_str!("mastra/agents/demo-agent.md");
const DEMO_PROMPT: &str = include_str!("mastra/resources/hello.txt");

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    init_tracing("info");

    let agent = Agent::new(AgentConfig {
        id: "demo-agent".to_owned(),
        name: "Demo Agent".to_owned(),
        instructions: DEMO_AGENT_INSTRUCTIONS.trim().to_owned(),
        description: Some("Starter agent generated by create-mastra".to_owned()),
        model: Arc::new(StaticModel::echo()),
        tools: Vec::new(),
        memory: Some(Arc::new(Memory::in_memory())),
        memory_config: MemoryConfig::default(),
    });

    let response = agent.generate(AgentGenerateRequest {
        prompt: DEMO_PROMPT.trim().to_owned(),
        thread_id: None,
        resource_id: Some("starter".to_owned()),
        run_id: None,
        max_steps: None,
        request_context: RequestContext::new().with_resource_id("starter"),
        ..Default::default()
    }).await?;

    println!(
        "starter graph assets loaded: manifest={} tool={} workflow={}",
        STARTER_MANIFEST.lines().count(),
        DEMO_TOOL_SPEC.lines().count(),
        DEMO_WORKFLOW_SPEC.lines().count(),
    );
    println!("agent response: {}", response.text);
    Ok(())
}
"#
    .to_owned()
}

pub fn render_starter_manifest(project_name: &str) -> String {
    format!(
        r#"{{
  "schema_version": 1,
  "app_name": "{project_name}",
  "entrypoint": "src/main.rs",
  "mastra_dir": "src/mastra",
  "resources": [
    {{
      "id": "starter-prompt",
      "kind": "text",
      "path": "resources/hello.txt"
    }}
  ],
  "memories": [
    {{
      "id": "default-memory",
      "path": "memories/default-memory.json"
    }}
  ],
  "tools": [
    {{
      "id": "demo-sum",
      "path": "tools/demo-sum.json"
    }}
  ],
  "agents": [
    {{
      "id": "demo-agent",
      "path": "agents/demo-agent.json"
    }}
  ],
  "workflows": [
    {{
      "id": "demo-workflow",
      "path": "workflows/demo-workflow.json"
    }}
  ]
}}
"#
    )
}

pub fn render_memory_manifest() -> String {
    r#"{
  "id": "default-memory",
  "kind": "in_memory",
  "name": "Default Memory",
  "description": "Starter in-memory conversation store used by the demo agent."
}
"#
    .to_owned()
}

pub fn render_tool_manifest() -> String {
    r#"{
  "id": "demo-sum",
  "kind": "sum",
  "name": "Demo Sum Tool",
  "description": "Adds two integers so the CLI loader has a concrete tool node to register.",
  "input": {
    "left": 2,
    "right": 3
  },
  "output": {
    "sum": 5
  }
}
"#
    .to_owned()
}

pub fn render_agent_manifest() -> String {
    r#"{
  "id": "demo-agent",
  "kind": "echo",
  "name": "Demo Agent",
  "instructions_path": "agents/demo-agent.md",
  "memory": "default-memory",
  "tools": [
    "demo-sum"
  ],
  "model": {
    "kind": "echo"
  }
}
"#
    .to_owned()
}

pub fn render_workflow_manifest() -> String {
    r#"{
  "id": "demo-workflow",
  "kind": "static_json",
  "name": "Demo Workflow",
  "description": "Starter workflow graph for CLI project loading.",
  "steps": [
    {
      "id": "prepare_input",
      "kind": "static_json",
      "output": {
        "left": 2,
        "right": 3
      }
    },
    {
      "id": "call_demo_tool",
      "kind": "tool",
      "tool": "demo-sum"
    },
    {
      "id": "finish",
      "kind": "static_json",
      "output": {
        "status": "ok",
        "message": "starter workflow completed"
      }
    }
  ]
}
"#
    .to_owned()
}

pub fn render_agent_instructions() -> String {
    r#"# Demo Agent

You are the starter agent generated by `create-mastra`.

Keep answers concise and grounded in the prompt.
Echo the request in a friendly sentence so the default `StaticModel::echo()` run is easy to verify.
"#
    .to_owned()
}

pub fn render_prompt_example() -> String {
    "Hello from create-mastra and src/mastra resources.\n".to_owned()
}

pub fn render_readme(project_name: &str) -> String {
    format!(
        r#"# {project_name}

Manifest-driven Rust starter generated by `create-mastra`.

## Run

```bash
cargo run
```

## What It Does

- boots a real `mastra-core` agent
- enables in-memory message persistence through `mastra-memory`
- initializes tracing via `mastra-loggers`
- stores a loader-friendly project graph in `src/mastra/mastra.json`
- ships one demo memory, tool, agent, and workflow under `src/mastra/`
- keeps agent instructions and example prompt in `src/mastra/`

## Starter Layout

- `src/main.rs`: runnable bootstrap
- `src/mastra/mastra.json`: starter manifest for CLI/project loaders
- `src/mastra/memories/default-memory.json`: default memory node
- `src/mastra/tools/demo-sum.json`: demo tool node
- `src/mastra/agents/demo-agent.json`: demo agent node
- `src/mastra/agents/demo-agent.md`: agent instructions
- `src/mastra/workflows/demo-workflow.json`: demo workflow node
- `src/mastra/resources/hello.txt`: example prompt

Edit `src/main.rs` to replace the echo model with your own agent logic, or grow the manifest/resources layout as your project evolves.
"#
    )
}

pub fn render_env_example() -> String {
    r#"# Add provider credentials here when you move beyond the echo model.
# OPENAI_API_KEY=your-key
"#
    .to_owned()
}

pub fn default_repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("workspace root")
        .to_path_buf()
}

pub fn scaffold(path: &Path, repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let project_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("mastra-app");
    let src_dir = path.join("src");
    let mastra_dir = src_dir.join("mastra");
    let memory_dir = mastra_dir.join("memories");
    let tool_dir = mastra_dir.join("tools");
    let agent_dir = mastra_dir.join("agents");
    let workflow_dir = mastra_dir.join("workflows");
    let resource_dir = mastra_dir.join("resources");

    fs::create_dir_all(&src_dir)?;
    fs::create_dir_all(&memory_dir)?;
    fs::create_dir_all(&tool_dir)?;
    fs::create_dir_all(&agent_dir)?;
    fs::create_dir_all(&workflow_dir)?;
    fs::create_dir_all(&resource_dir)?;
    fs::write(
        path.join("Cargo.toml"),
        render_manifest(project_name, repo_root),
    )?;
    fs::write(path.join("src/main.rs"), render_main_rs())?;
    fs::write(
        path.join(STARTER_MANIFEST_PATH),
        render_starter_manifest(project_name),
    )?;
    fs::write(path.join(STARTER_MEMORY_PATH), render_memory_manifest())?;
    fs::write(path.join(STARTER_TOOL_PATH), render_tool_manifest())?;
    fs::write(path.join(STARTER_AGENT_SPEC_PATH), render_agent_manifest())?;
    fs::write(
        path.join(STARTER_AGENT_INSTRUCTIONS_PATH),
        render_agent_instructions(),
    )?;
    fs::write(path.join(STARTER_WORKFLOW_PATH), render_workflow_manifest())?;
    fs::write(path.join(STARTER_PROMPT_PATH), render_prompt_example())?;
    fs::write(path.join("README.md"), render_readme(project_name))?;
    fs::write(path.join(".env.example"), render_env_example())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use tempfile::tempdir;

    use super::{
        STARTER_AGENT_INSTRUCTIONS_PATH, STARTER_AGENT_SPEC_PATH, STARTER_MANIFEST_PATH,
        STARTER_MEMORY_PATH, STARTER_PROMPT_PATH, STARTER_TOOL_PATH, STARTER_WORKFLOW_PATH,
        render_agent_instructions, render_agent_manifest, render_env_example, render_main_rs,
        render_manifest, render_memory_manifest, render_prompt_example, render_readme,
        render_starter_manifest, render_tool_manifest, render_workflow_manifest, scaffold,
    };

    #[test]
    fn render_manifest_points_to_local_workspace_crates() {
        let repo_root = Path::new("/tmp/mastra-rs");
        let manifest = render_manifest("demo-app", repo_root);

        assert!(manifest.contains("name = \"demo-app\""));
        assert!(manifest.contains("mastra-core = { path = \"/tmp/mastra-rs/packages/core\" }"));
        assert!(manifest.contains("mastra-memory = { path = \"/tmp/mastra-rs/packages/memory\" }"));
        assert!(
            manifest.contains("mastra-loggers = { path = \"/tmp/mastra-rs/packages/loggers\" }")
        );
    }

    #[test]
    fn render_main_rs_bootstraps_a_real_agent() {
        let main_rs = render_main_rs();

        assert!(main_rs.contains("StaticModel::echo()"));
        assert!(main_rs.contains("Memory::in_memory()"));
        assert!(main_rs.contains("include_str!(\"mastra/mastra.json\")"));
        assert!(main_rs.contains("DEMO_TOOL_SPEC"));
        assert!(main_rs.contains("DEMO_WORKFLOW_SPEC"));
        assert!(main_rs.contains("DEMO_AGENT_INSTRUCTIONS"));
        assert!(main_rs.contains("DEMO_PROMPT"));
    }

    #[test]
    fn render_starter_manifest_points_to_generated_project_graph_assets() {
        let manifest = render_starter_manifest("demo-app");

        assert!(manifest.contains("\"app_name\": \"demo-app\""));
        assert!(manifest.contains("\"memories\""));
        assert!(manifest.contains("\"tools\""));
        assert!(manifest.contains("\"mastra_dir\": \"src/mastra\""));
        assert!(manifest.contains("\"path\": \"agents/demo-agent.json\""));
        assert!(manifest.contains("\"path\": \"workflows/demo-workflow.json\""));
    }

    #[test]
    fn render_static_component_manifests_cover_memory_tool_agent_and_workflow_nodes() {
        let memory = render_memory_manifest();
        let tool = render_tool_manifest();
        let agent = render_agent_manifest();
        let workflow = render_workflow_manifest();

        assert!(memory.contains("\"kind\": \"in_memory\""));
        assert!(tool.contains("\"kind\": \"sum\""));
        assert!(agent.contains("\"kind\": \"echo\""));
        assert!(agent.contains("\"memory\": \"default-memory\""));
        assert!(workflow.contains("\"kind\": \"static_json\""));
        assert!(workflow.contains("\"tool\": \"demo-sum\""));
    }

    #[test]
    fn render_agent_instructions_and_prompt_example_are_human_editable_assets() {
        let instructions = render_agent_instructions();
        let prompt = render_prompt_example();

        assert!(instructions.contains("# Demo Agent"));
        assert!(instructions.contains("starter agent"));
        assert!(prompt.contains("src/mastra resources"));
    }

    #[test]
    fn render_readme_mentions_generated_starter_and_run_command() {
        let readme = render_readme("demo-app");

        assert!(readme.contains("# demo-app"));
        assert!(readme.contains("cargo run"));
        assert!(readme.contains("create-mastra"));
        assert!(readme.contains("src/mastra/mastra.json"));
        assert!(readme.contains("demo workflow node"));
    }

    #[test]
    fn render_env_example_documents_provider_placeholder() {
        let env_example = render_env_example();

        assert!(env_example.contains("OPENAI_API_KEY"));
        assert!(env_example.contains("echo model"));
    }

    #[test]
    fn scaffold_writes_runnable_starter_files() {
        let temp = tempdir().expect("tempdir");
        let target = temp.path().join("demo-app");
        let repo_root = Path::new("/repo/mastra-rs");

        scaffold(&target, repo_root).expect("scaffold should succeed");

        let manifest = fs::read_to_string(target.join("Cargo.toml")).expect("manifest");
        let main_rs = fs::read_to_string(target.join("src/main.rs")).expect("main");
        let starter_manifest =
            fs::read_to_string(target.join(STARTER_MANIFEST_PATH)).expect("starter manifest");
        let memory_manifest =
            fs::read_to_string(target.join(STARTER_MEMORY_PATH)).expect("memory manifest");
        let tool_manifest =
            fs::read_to_string(target.join(STARTER_TOOL_PATH)).expect("tool manifest");
        let agent_manifest =
            fs::read_to_string(target.join(STARTER_AGENT_SPEC_PATH)).expect("agent manifest");
        let instructions = fs::read_to_string(target.join(STARTER_AGENT_INSTRUCTIONS_PATH))
            .expect("agent instructions");
        let workflow_manifest =
            fs::read_to_string(target.join(STARTER_WORKFLOW_PATH)).expect("workflow manifest");
        let prompt = fs::read_to_string(target.join(STARTER_PROMPT_PATH)).expect("prompt example");
        let readme = fs::read_to_string(target.join("README.md")).expect("readme");
        let env_example = fs::read_to_string(target.join(".env.example")).expect("env example");

        assert!(manifest.contains("/repo/mastra-rs/packages/core"));
        assert!(main_rs.contains("starter graph assets loaded"));
        assert!(starter_manifest.contains("\"app_name\": \"demo-app\""));
        assert!(starter_manifest.contains("\"memories\""));
        assert!(memory_manifest.contains("\"default-memory\""));
        assert!(tool_manifest.contains("\"demo-sum\""));
        assert!(agent_manifest.contains("\"demo-agent\""));
        assert!(instructions.contains("Demo Agent"));
        assert!(workflow_manifest.contains("\"demo-workflow\""));
        assert!(prompt.contains("Hello from create-mastra"));
        assert!(readme.contains("# demo-app"));
        assert!(env_example.contains("OPENAI_API_KEY"));
    }
}
