use std::{
    fs,
    path::{Path, PathBuf},
};

pub fn render_manifest(project_name: &str, repo_root: &Path) -> String {
    format!(
        r#"[package]
name = "{project_name}"
version = "0.1.0"
edition = "2024"

[dependencies]
mastra-core = {{ path = "{core_path}" }}
mastra-memory = {{ path = "{memory_path}" }}
mastra-loggers = {{ path = "{loggers_path}" }}
tokio = {{ version = "1.47.1", features = ["full"] }}
"#,
        core_path = repo_root.join("packages/core").display(),
        memory_path = repo_root.join("packages/memory").display(),
        loggers_path = repo_root.join("packages/loggers").display(),
    )
}

pub fn render_main_rs() -> String {
    r#"use std::sync::Arc;

use mastra_core::{Agent, AgentConfig, AgentGenerateRequest, MemoryConfig, RequestContext, StaticModel};
use mastra_loggers::init_tracing;
use mastra_memory::Memory;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    init_tracing("info");

    let agent = Agent::new(AgentConfig {
        id: "demo-agent".to_owned(),
        name: "Demo Agent".to_owned(),
        instructions: "Echo the incoming prompt.".to_owned(),
        description: Some("Starter agent generated by create-mastra".to_owned()),
        model: Arc::new(StaticModel::echo()),
        tools: Vec::new(),
        memory: Some(Arc::new(Memory::in_memory())),
        memory_config: MemoryConfig::default(),
    });

    let response = agent.generate(AgentGenerateRequest {
        prompt: "Hello from create-mastra".to_owned(),
        thread_id: None,
        resource_id: Some("starter".to_owned()),
        run_id: None,
        max_steps: None,
        request_context: RequestContext::new().with_resource_id("starter"),
        ..Default::default()
    }).await?;

    println!("agent response: {}", response.text);
    Ok(())
}
"#
    .to_owned()
}

pub fn render_readme(project_name: &str) -> String {
    format!(
        r#"# {project_name}

Minimal Rust starter generated by `create-mastra`.

## Run

```bash
cargo run
```

## What It Does

- boots a real `mastra-core` agent
- enables in-memory message persistence through `mastra-memory`
- initializes tracing via `mastra-loggers`

Edit `src/main.rs` to replace the echo model with your own agent logic.
"#
    )
}

pub fn render_env_example() -> String {
    r#"# Add provider credentials here when you move beyond the echo model.
# OPENAI_API_KEY=your-key
"#
    .to_owned()
}

pub fn default_repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("workspace root")
        .to_path_buf()
}

pub fn scaffold(path: &Path, repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(path.join("src"))?;
    fs::write(
        path.join("Cargo.toml"),
        render_manifest(
            &path
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or("mastra-app"),
            repo_root,
        ),
    )?;
    fs::write(path.join("src/main.rs"), render_main_rs())?;
    fs::write(
        path.join("README.md"),
        render_readme(
            &path
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or("mastra-app"),
        ),
    )?;
    fs::write(path.join(".env.example"), render_env_example())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use tempfile::tempdir;

    use super::{render_env_example, render_main_rs, render_manifest, render_readme, scaffold};

    #[test]
    fn render_manifest_points_to_local_workspace_crates() {
        let repo_root = Path::new("/tmp/mastra-rs");
        let manifest = render_manifest("demo-app", repo_root);

        assert!(manifest.contains("name = \"demo-app\""));
        assert!(manifest.contains("mastra-core = { path = \"/tmp/mastra-rs/packages/core\" }"));
        assert!(manifest.contains("mastra-memory = { path = \"/tmp/mastra-rs/packages/memory\" }"));
        assert!(
            manifest.contains("mastra-loggers = { path = \"/tmp/mastra-rs/packages/loggers\" }")
        );
    }

    #[test]
    fn render_main_rs_bootstraps_a_real_agent() {
        let main_rs = render_main_rs();

        assert!(main_rs.contains("StaticModel::echo()"));
        assert!(main_rs.contains("Memory::in_memory()"));
        assert!(main_rs.contains("agent.generate"));
    }

    #[test]
    fn render_readme_mentions_generated_starter_and_run_command() {
        let readme = render_readme("demo-app");

        assert!(readme.contains("# demo-app"));
        assert!(readme.contains("cargo run"));
        assert!(readme.contains("create-mastra"));
    }

    #[test]
    fn render_env_example_documents_provider_placeholder() {
        let env_example = render_env_example();

        assert!(env_example.contains("OPENAI_API_KEY"));
        assert!(env_example.contains("echo model"));
    }

    #[test]
    fn scaffold_writes_runnable_starter_files() {
        let temp = tempdir().expect("tempdir");
        let target = temp.path().join("demo-app");
        let repo_root = Path::new("/repo/mastra-rs");

        scaffold(&target, repo_root).expect("scaffold should succeed");

        let manifest = fs::read_to_string(target.join("Cargo.toml")).expect("manifest");
        let main_rs = fs::read_to_string(target.join("src/main.rs")).expect("main");
        let readme = fs::read_to_string(target.join("README.md")).expect("readme");
        let env_example = fs::read_to_string(target.join(".env.example")).expect("env example");

        assert!(manifest.contains("/repo/mastra-rs/packages/core"));
        assert!(main_rs.contains("println!(\"agent response: {}\", response.text);"));
        assert!(readme.contains("# demo-app"));
        assert!(env_example.contains("OPENAI_API_KEY"));
    }
}
